# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |

- task: Docker@2
  inputs:
    containerRegistry: 'voteapp_Brief8_GS'
    repository: 'Voteapp_Brief8_GS'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'